# Generated by Django 5.0 on 2024-01-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expenditure',
            field=models.FloatField(default=0),
        ),
    ]
