# Generated by Django 5.0 on 2024-01-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_profile_balance_alter_profile_expenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=models.IntegerField(), null=True),
        ),
    ]
