# Generated by Django 5.0 on 2024-01-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(blank=True, default=models.IntegerField(), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expenditure',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
